name: as241s4_t13_appmovil
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1
  dio: ^5.4.3+1
  connectivity_plus: ^6.0.4
  logger: ^2.5.0

  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  flutter_blurhash: ^0.9.1

  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2
  get_it: ^7.7.0
  provider: ^6.1.2
  equatable: ^2.0.5

  get: ^4.6.6
  go_router: ^14.2.1
  auto_route: 10.2.0

  google_fonts: ^6.2.1
  flex_color_scheme: ^8.1.1

  dropdown_button2: ^2.0.4
  cupertino_icons: ^1.0.8
  dropdown_search: ^5.0.6
  flutter_animate: ^4.5.0
  animations: ^2.0.11
  rive: ^0.13.0
  lottie: ^3.1.2
  motion: ^2.0.1
  simple_animations: ^5.1.0
  flutter_staggered_animations: ^1.1.1
  liquid_swipe: ^3.1.0
  animated_text_kit: ^4.2.3

  flutter_screenutil: ^5.9.1
  responsive_framework: ^1.4.0

  flutter_local_notifications: ^17.2.2
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.2
  package_info_plus: ^8.0.1

  path_provider: ^2.1.3
  url_launcher: ^6.3.1
  intl: ^0.19.0
  flutter_native_splash: ^2.4.2
  flutter_launcher_icons: ^0.13.1
  fl_chart: ^0.64.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/header/
    - assets/background/
    - assets/sidebar/
    - assets/card_user/
    - assets/formUser/
    - assets/icon/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"